### ISSUE TITLE
Confused by dotnet requirements and setup

### ISSUE THREAD

**Issue by CarlKCarlK** [matgla/Renode_RP2040#10]
Greetings. I'm still running fine on Windows, but I'm trying to write up instructions on how to run on Linux, etc. When I try install on a new version of Ubuntu 24, I'm seeing this error in `Renode_RP2040/emulation/peripherals/memory/memory_alias.cs`
```
(tests) carlk@carlk23:~/dua_blinka/tests$ dotnet --version
9.0.101
(tests) carlk@carlk23:~/dua_blinka/tests$ renode --version
Renode v1.15.3.4367
  build: e1a64160-202412070324
  build type: Release
  runtime: .NET 6.0.36
(tests) carlk@carlk23:~/dua_blinka/tests$ renode --console run_dua_blinka.resc
14:58:21.1288 [INFO] Loaded monitor commands from: /home/carlk/renode/scripts/monitor.py
14:58:21.1318 [WARNING] On dotnet configuration option "collapse-repeated-log-entries" is not supported in console mode on unix-like system. It will be set to false.
Renode, version 1.15.3.4367 (e1a64160-202412070324)

(monitor) i $CWD/run_dua_blinka.resc
14:58:21.2442 [INFO] Including script: /home/carlk/dua_blinka/tests/run_dua_blinka.resc
Current 'PATH' value is: /home/carlk/renode;/home/carlk/dua_blinka/tests;/home/carlk/Renode_RP2040
14:58:21.2593 [INFO] System bus created.
Errors during compilation or loading:
Could not compile assembly from: /home/carlk/Renode_RP2040/emulation/peripherals/memory/memory_alias.cs
(8,67): error CS0535: 'MemoryAlias' does not implement interface member 'IBytePeripheral.ReadByte(long)'
(8,67): error CS0535: 'MemoryAlias' does not implement interface member 'IBytePeripheral.WriteByte(long, byte)'
(8,67): error CS0535: 'MemoryAlias' does not implement interface member 'IWordPeripheral.ReadWord(long)'
(8,67): error CS0535: 'MemoryAlias' does not implement interface member 'IWordPeripheral.WriteWord(long, ushort)'
(8,67): error CS0535: 'MemoryAlias' does not implement interface member 'IMultibyteWritePeripheral.ReadBytes(long, int, ICPU)'
(8,67): error CS0535: 'MemoryAlias' does not implement interface member 'IMultibyteWritePeripheral.WriteBytes(long, byte[], int, int, ICPU)'
(8,67): error CS0535: 'MemoryAlias' does not implement interface member 'IQuadWordPeripheral.ReadQuadWord(long)'
(8,67): error CS0535: 'MemoryAlias' does not implement interface member 'IQuadWordPeripheral.WriteQuadWord(long, ulong)'
(rasbperry_pico)
```

Which looks like some .NET compatibility issue. I've tried installed both dotnet 6 and dotnet 9 and use release of renode from renode *.deb, renode portable with dotnot included, and renode portable without dotnet. No combination seems to work.

What dotnet version are you using on Linux? Which release package of renode to you use?

Thanks for any help. I'm hoping to share this with some folks at the Seattle Rust User group on Thursday. We've been programming Picos.

**Comment by matgla** [comment]
Hi, 
You got a renode version with the latest renode-infrastructure somehow. There were API changes in IMemory. On my Linux installation, I am using a mono version of renode from https://github.com/renode/renode/releases/tag/v1.15.3 (
renode-1.15.3.linux-portable.tar.gz ) -> https://github.com/renode/renode/releases/download/v1.15.3/renode-1.15.3.linux-portable.tar.gz 

```
[mateusz@archlinux renode_1.15.3_portable]$ ./renode --version
Renode v1.15.3.18516
  build: 03756cb5-202409171017
  build type: Release
  runtime: Mono 4.0.30319.42000
```
With dotnet: 
```
dotnet --version
8.0.110
``` 

But that issue is definitely not related to dotnet, but rather to Renode. 

Your Renode environment contains changes from 28.11.2024 and the latest release is from 18.09.2024, which is strange to me. 

Can I ask if you downloaded renode from: https://github.com/renode/renode/releases/tag/v1.15.3 

Could you also verify with `which renode` if the correct renode was placed in PATH? 

Best regards, 
Mateusz Stadnik

**Comment by matgla** [comment]
I see. If you followed the manual from renode readme, they placed nightly builds in their manual. Please download the latest stable version. And please use mono, since I have some problems with Linux .net release.  Something bad happens to paths, but maybe it's a problem only on my machine.

**Comment by CarlKCarlK** [comment]
Thanks! It's working. Here is what I say:


Install the [Renode emulator](https://github.com/renode/renode/releases). On Linux, you'll want [renode-1.15.3.linux-portable.tar.gz](https://github.com/renode/renode/releases/download/v1.15.3/renode-1.15.3.linux-portable.tar.gz) which was created with Mono 4.0 and works with .NET 8 or 9.
```
wget https://github.com/renode/renode/releases/download/v1.15.3/renode-1.15.3.linux-portable.tar.gz -O renode-1.15.3.linux-portable.tar.gz
mkdir -p ~/renode && tar -xzf renode-1.15.3.linux-portable.tar.gz -C ~/renode --strip-components=1
echo 'export PATH=$PATH:~/renode' >> ~/.bashrc
source ~/.bashrc
renode --version
```
On Windows, you'll want the [renode_1.15.3.msi](https://github.com/renode/renode/releases/download/v1.15.3/renode_1.15.3.msi), but you'll may need to tell your virus checker that it is OK. It was created with .NET framework 4.0 and works with .NET 8 or 9.
