### ISSUE TITLE
Default LED color is not working

### ISSUE THREAD

**Issue by matgla** [matgla/Renode_RP2040#13]
The default LED color in the GUI is not working, and this needs to be fixed.

**Comment by CarlKCarlK** [comment]
Is this the bug in which the LED doesn't blink until you edit its color?

**Comment by matgla** [comment]
Yes, I already have a fix, but it waits for time to test it and deliver.

**Comment by matgla** [comment]
Closed with: https://github.com/matgla/Renode_RP2040/releases/tag/v0.2.4

**Comment by CarlKCarlK** [comment]
Looks great. thanks!
