### ISSUE TITLE
Wish button looked nicer

### ISSUE THREAD

**Issue by CarlKCarlK** [matgla/Renode_RP2040#15]
Greetings. It's working great and is even now useable. Here are some minor issues that I notice:

As you mentioned once, the current button is hard to see, and I find myself accidentally pressing the LED.

Thanks for your work on this project.

**Comment by matgla** [comment]
Hi, 
Yes, it is planned todo.

**Comment by matgla** [comment]
Closed with: https://github.com/matgla/Renode_RP2040/releases/tag/v0.2.4

**Comment by CarlKCarlK** [comment]
Look great. Thanks, again.
