### ISSUE TITLE
Replace "React app" as the name and icon of the web page

### ISSUE THREAD

**Issue by CarlKCarlK** [matgla/Renode_RP2040#16]
[Again, this is minor]
When I do http://localhost:1234/ the browser tab shows "React App" and the React icon.

**Comment by matgla** [comment]
Yes, I haven't changed it yet, so it is showing default react naming. It is to be done for some unknown future yet.

**Comment by matgla** [comment]
Closed with: https://github.com/matgla/Renode_RP2040/releases/tag/v0.2.4

**Comment by CarlKCarlK** [comment]
Nice
