### ISSUE TITLE
Document how to use in CI testing with scripted time and button pushes

### ISSUE THREAD

**Issue by CarlKCarlK** [matgla/Renode_RP2040#18]
If this is possible and explained, it would make CI testing of Pico programs much easier.

What I'd like to be able to do:
* Be able to script button pushes and the passage of time (deterministically, ideally)
* Check that the LEDs that I expect to be on really are on.

**Comment by matgla** [comment]
Yes, you can, 
Testing is described in renode documentation: https://renode.readthedocs.io/en/latest/introduction/testing.html 

You can also check tests for LEDs and buttons: 
https://github.com/matgla/Renode_RP2040/tree/main/tests/testcases/pio/pio_blink
https://github.com/matgla/Renode_RP2040/tree/main/tests/testcases/button

**Comment by CarlKCarlK** [comment]
Perfect!
