### ISSUE TITLE
Add support for 7-segment display

### ISSUE THREAD

**Issue by matgla** [matgla/Renode_RP2040#7]
Prioritize https://github.com/raspberrypi/pico-examples/tree/master/gpio/hello_7segment to add support for 7-segment displays in both robot framework and UI.

**Comment by Mes-ser** [comment]
Maybe this will help with GUI implementation
[betrousted.memlcd.cs](https://github.com/betrusted-io/xous-core/blob/main/emulation/peripherals/memlcd.cs)
And if I get it right, after running:
`showAnalyzer sysbus.memlcd`
that window appear: 
![image](https://github.com/user-attachments/assets/6a74fd59-6fe4-47d1-9fab-29be693d7f0f)

**Comment by matgla** [comment]
@Mes-ser: Thanks! For now, I think I'll stick to Python + React. My idea is to detect widgets automatically and then allow users to create layouts. 

@CarlKCarlK: Thanks, I am trying to make a framework to handle all widgets in the same manner, and then 7-segment displays should be relatively simple to add.

**Comment by matgla** [comment]
@CarlKCarlK: If you wish to try the new UI that is coming out (v0.2.1), changes necessary to run_blinky.resc or manual visualization starting: 
```
startVisualization 1234 
visualizationSetBoardElement led
visualizationLoadLayout $ORIGIN/blinky_layout.json 
```
`visualizationSetBoardElement` - changes board led to hidden (right now, later it will be rendered on top of board image) 
`visualizationLoadLayout` - loads layout from JSON, layout may be created by moving element over UI and saving with the save layout button 

Example JSON file `blinky_layout`: 
```
{
  "boards": [
    {
      "mcus": {
        "mcu": {
          "position": {
            "column": 10,
            "row": 2
          }
        }
      },
      "leds": {
        "led": {
          "position": {
            "column": 14,
            "row": 1
          },
          "color": "#e91e63"
        },
        "led1": {
          "position": {
            "column": 12,
            "row": 1
          },
          "color": "#3f51b5"
        },
        "led2": {
          "position": {
            "column": 10,
            "row": 1
          },
          "color": "#607d8b"
        }
      },
      "buttons": {
        "button": {
          "position": {
            "column": 10,
            "row": 6
          }
        }
      }
    }
  ]
}

```

**Comment by CarlKCarlK** [comment]
That cool! It's kind of working for me with LEDs.  This picture shows my suggested default the origination for the breadboard and the Pico. Some people rotate both by 180 degrees.
![image](https://github.com/user-attachments/assets/a40d10b1-56a8-4fa7-8b39-4af4e322706b)

**Comment by matgla** [comment]
I implemented basic support for 7segment displays. 
The colon may not be rendered properly, but digits and dots should be working. 
I need a few minutes to do the cleanup, then I'll deliver the v0.2.2 version. 
@CarlKCarlK : for your clock example I used below scripts:
`clocks_layout.json`:
```
{
  "boards": [
    {
      "mcus": {
        "mcu": {
          "position": {
            "column": 49,
            "row": 4
          }
        }
      },
      "leds": {
        "led1": {
          "position": {
            "column": 60,
            "row": 1
          },
          "color": "#8bc34a"
        }
      },
      "buttons": {
        "button": {
          "position": {
            "column": 44,
            "row": 11
          }
        }
      },
      "segmentDisplays": {
        "segment_display": {
          "position": {
            "column": 2,
            "row": 6
          },
          "color": "#03a9f4"
        }
      }
    }
  ]
}
```
`raspberry_clock.repl`
```
using "boards/raspberry_pico.repl"

led1: Miscellaneous.LED @ gpio 0

segment_display: Miscellaneous.SegmentDisplay @ gpio 1 {
    cells: 4;
    segments: 8;
    colon: 2
}

gpio: 
    0 -> led1@0
    [1-12] -> segment_display@[0-11]


button: Miscellaneous.Button @ gpio 13 
    -> gpio@13
```
`run_clock.resc`
```
$platform_file=@raspberry_clock.repl
$global.FIRMWARE=$ORIGIN/clock
include @run_firmware.resc

startVisualization 1234

visualizationSetBoardElement led 
visualizationLoadLayout $ORIGIN/clock_layout.json
```
Regarding layouts, I am not going to add component rotation for now. I think it's enough as it is. The layout itself is modifiable with the mouse. After changes, a new layout can be exported with the `save` button in the layout section. 
 
 I am going to release a YouTube episode about my renode progress. Could I use your blinky and clock example inside? They are best to show GUI functionality right now!

**Comment by CarlKCarlK** [comment]
Don't worry about the colon. The decimal points are more common

________________________________

**Comment by matgla** [comment]
I know that's why I skipped that part for now. 
I have some bugs, that sometimes display is almost invisible. 
Refreshing the browser helps almost always, but when not zooming seems to be working always. 
I'll try to find what causes that during the week. And I'll change the asset for a button, it's barely visible. 
But it is working more or less for me, so you can try using it with your clock example :) 

Moreover, the layout from v0.2.1 is not compatible with v0.2.2, so please update your layout for blinky as well, I had to change the grid size for better placement of the display.

**Comment by CarlKCarlK** [comment]
It's working!!!! This will be so great for Rust programmers who want to know a bit about embedded programming but don't have hardware.

**Comment by CarlKCarlK** [comment]
I nice button will be great. Do you know why my two LED, 1 button setup isn't working, now?

I'm getting:
```
Spawned process with PID: 2643132
There was an error executing command 'startVisualization 1212'
Command 'startVisualization 1212' failed
        Multiple targets could match: __getitem__(tuple), __getitem__(Array[object]), __getitem__(Array[object])
```
I'm running `renode --console run_dua_blinka.resc` where that file is:
```
$platform_file=@raspberry_dua_blinka.repl
$global.FIRMWARE=@../target/thumbv6m-none-eabi/debug/dua_blinka
path add @c:/deldir/1124/Renode_RP2040
include @run_firmware.resc
startVisualization 1212

visualizationSetBoardElement led 
visualizationLoadLayout dua_blinka_layout.json
```
and `raspberry_dua_blinka.repl` is:

```
using "boards/raspberry_pico.repl"

led1: Miscellaneous.LED @ gpio 2
led2: Miscellaneous.LED @ gpio 3

gpio: 
    2 -> led1@0
    3 -> led2@0

button: Miscellaneous.Button @ gpio 13 
    -> gpio@13
```

**Comment by CarlKCarlK** [comment]
It's working. Thanks! (I needed one workaround. At first the LEDs are the wrong color and don't show blinking, but if I edit their color, everything works).

**Comment by matgla** [comment]
Great! 
I know about a few problems with GUI usage, sometimes colors are not exported to the layout file. 
And if the color is not loaded from the file or set it will not blink. 

Some problems have already been fixed in the branch where I am working on adding tests for the 7segment display. 
However, I need time to finish tests and figure out why the segment display is wrongly rendered sometimes.
